version: "3.5"

services: 
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: sql-server-1433
        hostname: sql-server-1
        user: root
        env_file: 
            - .env
        ports:
            - 1433:1433
        volumes:
            - ~/sqlserver-data:/var/opt/mssql
            # - ~/sqlserver-data/data:/var/opt/mssql/data
            # - ~/sqlserver-data/log:/var/opt/mssql/log
            # - ~/sqlserver-data/secrets:/var/opt/mssql/secrets
        networks: 
            - sqlserver-net

networks:
    sqlserver-net:
        driver: bridge